name: release

on:
  release:
    types:
      - created

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Build phar
        run: php -d phar.readonly=0 bin/build -"$RELEASE_VERSION"

      - name: Verify version
        run: php deployer.phar -V

      - name: Upload phar
        run: gh release upload "$RELEASE_VERSION" deployer.phar
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}

      - name: Calculate sha1
        run: echo "SHA1=$(sha1sum deployer.phar | awk '{print $1;}')" >> $GITHUB_ENV

      - name: Deploy
        uses: deployphp/action@v1
        with:
          private-key: ${{ secrets.PRIVATE_KEY }}
          deployer-version: 7.0.0-beta.34
          dep: -f deploy.yaml update_manifest -o sha1="$SHA1" -o url="https://github.com/deployphp/deployer/releases/download/$RELEASE_VERSION/deployer.phar" -o version="$RELEASE_VERSION"
