name: release

on:
  release:
    types:
      - created

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Build phar
        run: php -d phar.readonly=0 bin/build -"$RELEASE_VERSION"

      - name: Verify version
        run: php deployer.phar -V

      - name: Upload phar
        run: gh release upload "$RELEASE_VERSION" deployer.phar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
